// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbiO1-Xc54McEJB4IFDZvrCl3D-1f0sHs',
    appId: '1:405624752300:web:01b64ff138d2b020d3f709',
    messagingSenderId: '405624752300',
    projectId: 'aqar-app-aca19',
    authDomain: 'aqar-app-aca19.firebaseapp.com',
    storageBucket: 'aqar-app-aca19.firebasestorage.app',
    measurementId: 'G-5VWCFHMFD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBtbz9yghaWWptueg1cr1QMhRZDvw1hrU',
    appId: '1:405624752300:android:21e936cf52815c67d3f709',
    messagingSenderId: '405624752300',
    projectId: 'aqar-app-aca19',
    storageBucket: 'aqar-app-aca19.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbiO1-Xc54McEJB4IFDZvrCl3D-1f0sHs',
    appId: '1:405624752300:web:5cb6a6f04ee40c3fd3f709',
    messagingSenderId: '405624752300',
    projectId: 'aqar-app-aca19',
    authDomain: 'aqar-app-aca19.firebaseapp.com',
    storageBucket: 'aqar-app-aca19.firebasestorage.app',
    measurementId: 'G-KVEKFY39PH',
  );
}
